"""Deterministic mock `NormalizerClient` — no network call."""

from app.core.config import settings


class MockNormalizerClient:
    async def normalize(
        self, content_list: list, markdown: str, known_categories: list[str]
    ) -> tuple[dict, str]:
        has_content = bool(markdown.strip()) or bool(content_list)
        if not has_content:
            return {
                "bank_name": None,
                "account_hint": None,
                "transactions": [],
            }, settings.chat_model.model_name

        return {
            "bank_name": "Mock Bank",
            "account_hint": "****0000",
            "transactions": [
                {
                    "transaction_date": "2026-01-01",
                    "merchant_raw": "Mock Merchant",
                    "ai_description": (
                        "A mock debit transaction of 100.0 at Mock Merchant, generated by "
                        "MockNormalizerClient for offline/test use — not derived from any "
                        "real document content."
                    ),
                    "category": "other",
                    "amount": 100.0,
                    "transaction_type": "debit",
                }
            ],
        }, settings.chat_model.model_name
